### ISSUE TITLE
[BUG] `ImportError: dlopen failed: cannot locate symbol "PyBytes_AsStringAndSize"`

### ISSUE THREAD

**Issue by GvozdevLeonid** [dashingsoft/pyarmor#1907]
Hello, I used pyarmor V8.5.11 to create an obfuscated file for android.aarch64 and android.armv7 platforms

using the command
`pyarmor gen --platform android.aarch64 --platform android.armv7 test.py`

For obfuscation I used a virtual environment with python 3.11.5 (exactly the same version is installed on android)

then I created a simple example to run the obfuscated code on android. when importing I get errors: 
```
Traceback (most recent call last):
File "/Users/leonidgvozdev/Work/example/.buildozer/android/app/main.py", line 31, in <module>
File "/Users/leonidgvozdev/Work/example/.buildozer/android/app/test.py", line 2, in <module>
File "/Users/leonidgvozdev/Work/ex ample/.buildozer/android/app/pyarmor_runtime_005896/__init__.py", line 55, in <module>
File "/Users/leonidgvozdev/Work/example/.buildozer/android/app/pyarmor_runtime_005896/__init__.py", line 52, in __pyarmor__
ImportError: dlopen failed: cannot locate symbol "PyBytes_AsStringAndSize" referenced by "/data/data/org.test.myapp/files/app/pyarmor_runtime_005896/android_aarch64/pyarmor_runtime.so"...
```

When building the apk file, I simply moved all the pyarmor_runtime.so files into the project file.
After studying the documentation, I did NOT install pyarmor on Android because it should work without this package

I tried this example

```
from ctypes import CFUNCTYPE, cdll, pythonapi, c_void_p, c_char_p, c_int

libc = cdll.LoadLibrary(None)

libpython = b'libpython3.11.so'
prototype = CFUNCTYPE(c_void_p, c_char_p, c_int)
dlopen = prototype(('dlopen', libc))
handle = dlopen(libpython, 0)

# handle = pythonapi._handle,
name = b'PyBytes_AsString'
prototype = CFUNCTYPE(c_void_p, c_void_p, c_char_p)
dlsym = prototype(('dlsym', libc))
print('Got api %s at %s' % (name, dlsym(handle, name)))
```

result:
`Got api b'PyBytes_AsString' at 474065958940`

**Comment by GvozdevLeonid** [comment]
I applied a patch for pyarmor_runtime.so
`patchelf --add-needed libpython3.11.so pyarmor_runtime.so`

now im getting another error

```
Traceback (most recent call last):
File "/Users/leonidgvozdev/Work/example/.buildozer/android/app/main.py", line 31, in <module>
File "/Users/leonidgvozdev/Work/example/.buildozer/android/app/test.py", line 2, in <module>
File "/Users/leonidgvozdev/Work/ex ample/.buildozer/android/app/pyarmor_runtime_005896/__init__.py", line 55, in <module>
File "/Users/leonidgvozdev/Work/example/.buildozer/android/app/pyarmor_runtime_005896/__init__.py", line 52, in __pyarmor__
RuntimeError: failed to get api PyCell_Get
```

**Comment by jondy** [comment]
Could you get `PyCell_Get` by example script like this
```python
    ...
    name = b'PyCell_Get'                                           
    prototype = CFUNCTYPE(c_void_p, c_void_p, c_char_p)                  
    dlsym = prototype(('dlsym', libc))                                   
    print('Got api %s at %s' % (name, dlsym(handle, name)))  
```

And in Android, check the symbol table by this command
```
objdump -T /path/to/libpython3.11.so | grep PyCell_Get
```

**Comment by GvozdevLeonid** [comment]
So. After installing the application and installing termux, I went into the program folder and got to the installed libraries.
Here is the result
<img width="720" alt="Снимок экрана 2024-08-21 в 16 22 00" src="https://github.com/user-attachments/assets/bf2a1a5c-f7de-4a92-9802-5118a9a694e9">

**Comment by jondy** [comment]
After check CPython source, I found the reason is that `PyCell_Get` is one api not in python3 limited api.

That is to say, your python interperter is built with `-D Py_LIMITED_API`, or same form in source like `#define Py_LIMITED_API 0x0311`

Do not built with this flag should solve this issue.

Generally the pre-release package includes `libpython3.so` and `libpython3.11.so`, if python interpreter is linked to `libpython3.so`, this error will be occurred 

Check it by `ldd /path/to/python`

**Comment by GvozdevLeonid** [comment]
I did some testing and found out that the required functions are available.

python-for-android runs its interpreter. They have a start.c file. I added some debug output


``` c

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#ifndef Py_PYTHON_H
#error Python headers needed to compile C extensions, please install development version of Python.
#else

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <dirent.h>
#include <jni.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <errno.h>

#include "bootstrap_name.h"

#ifndef BOOTSTRAP_USES_NO_SDL_HEADERS
#include "SDL.h"
#include "SDL_opengles2.h"
#endif
#include "android/log.h"

#define ENTRYPOINT_MAXLEN 128
#define LOG(n, x) __android_log_write(ANDROID_LOG_INFO, (n), (x))
#define LOGP(x) LOG("python", (x))

static PyObject *androidembed_log(PyObject *self, PyObject *args) {
  char *logstr = NULL;
  if (!PyArg_ParseTuple(args, "s", &logstr)) {
    return NULL;
  }
  LOG(getenv("PYTHON_NAME"), logstr);
  Py_RETURN_NONE;
}

static PyMethodDef AndroidEmbedMethods[] = {
    {"log", androidembed_log, METH_VARARGS, "Log on android platform"},
    {NULL, NULL, 0, NULL}};

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef androidembed = {PyModuleDef_HEAD_INIT, "androidembed",
                                          "", -1, AndroidEmbedMethods};

PyMODINIT_FUNC initandroidembed(void) {
  return PyModule_Create(&androidembed);
}
#else
PyMODINIT_FUNC initandroidembed(void) {
  (void)Py_InitModule("androidembed", AndroidEmbedMethods);
}
#endif

int dir_exists(char *filename) {
  struct stat st;
  if (stat(filename, &st) == 0) {
    if (S_ISDIR(st.st_mode))
      return 1;
  }
  return 0;
}

int file_exists(const char *filename) {
  FILE *file;
  if ((file = fopen(filename, "r"))) {
    fclose(file);
    return 1;
  }
  return 0;
}

/* int main(int argc, char **argv) { */
int main(int argc, char *argv[]) {

  char *env_argument = NULL;
  char *env_entrypoint = NULL;
  char *env_logname = NULL;
  char entrypoint[ENTRYPOINT_MAXLEN];
  int ret = 0;
  FILE *fd;

  LOGP("Initializing Python for Android");

  // Set a couple of built-in environment vars:
  setenv("P4A_BOOTSTRAP", bootstrap_name, 1);  // env var to identify p4a to applications
  env_argument = getenv("ANDROID_ARGUMENT");
  setenv("ANDROID_APP_PATH", env_argument, 1);
  env_entrypoint = getenv("ANDROID_ENTRYPOINT");
  env_logname = getenv("PYTHON_NAME");
  if (!getenv("ANDROID_UNPACK")) {
    /* ANDROID_UNPACK currently isn't set in services */
    setenv("ANDROID_UNPACK", env_argument, 1);
  }
  if (env_logname == NULL) {
    env_logname = "python";
    setenv("PYTHON_NAME", "python", 1);
  }

  // Set additional file-provided environment vars:
  LOGP("Setting additional env vars from p4a_env_vars.txt");
  char env_file_path[256];
  snprintf(env_file_path, sizeof(env_file_path),
           "%s/p4a_env_vars.txt", getenv("ANDROID_UNPACK"));
  FILE *env_file_fd = fopen(env_file_path, "r");
  if (env_file_fd) {
    char* line = NULL;
    size_t len = 0;
    while (getline(&line, &len, env_file_fd) != -1) {
      if (strlen(line) > 0) {
        char *eqsubstr = strstr(line, "=");
        if (eqsubstr) {
          size_t eq_pos = eqsubstr - line;

          // Extract name:
          char env_name[256];
          strncpy(env_name, line, sizeof(env_name));
          env_name[eq_pos] = '\0';

          // Extract value (with line break removed:
          char env_value[256];
          strncpy(env_value, (char*)(line + eq_pos + 1), sizeof(env_value));
          if (strlen(env_value) > 0 &&
              env_value[strlen(env_value)-1] == '\n') {
            env_value[strlen(env_value)-1] = '\0';
            if (strlen(env_value) > 0 &&
                env_value[strlen(env_value)-1] == '\r') {
              // Also remove windows line breaks (\r\n)
              env_value[strlen(env_value)-1] = '\0';
            } 
          }

          // Set value:
          setenv(env_name, env_value, 1);
        }
      }
    }
    fclose(env_file_fd);
  } else {
    LOGP("Warning: no p4a_env_vars.txt found / failed to open!");
  }

  LOGP("Changing directory to the one provided by ANDROID_ARGUMENT");
  LOGP(env_argument);
  chdir(env_argument);

#if PY_MAJOR_VERSION < 3
  Py_NoSiteFlag=1;
#endif

#if PY_MAJOR_VERSION < 3
  Py_SetProgramName("android_python");
#else
  Py_SetProgramName(L"android_python");
#endif

#if PY_MAJOR_VERSION >= 3
  /* our logging module for android
   */
  PyImport_AppendInittab("androidembed", initandroidembed);
#endif

  LOGP("Preparing to initialize python");

  // Set up the python path
  char paths[256];

  char python_bundle_dir[256];
  snprintf(python_bundle_dir, 256,
           "%s/_python_bundle", getenv("ANDROID_UNPACK"));
  if (dir_exists(python_bundle_dir)) {
    LOGP("_python_bundle dir exists");
    snprintf(paths, 256,
            "%s/stdlib.zip:%s/modules",
            python_bundle_dir, python_bundle_dir);

    LOGP("calculated paths to be...");
    LOGP(paths);

    #if PY_MAJOR_VERSION >= 3
        wchar_t *wchar_paths = Py_DecodeLocale(paths, NULL);
        Py_SetPath(wchar_paths);
    #endif

        LOGP("set wchar paths...");
  } else {
      LOGP("_python_bundle does not exist...this not looks good, all python"
           " recipes should have this folder, should we expect a crash soon?");
  }

  Py_Initialize();
  LOGP("Initialized python");

  /* ensure threads will work.
   */
  LOGP("AND: Init threads");
  PyEval_InitThreads();

// HERE IS THE DEBUG OUTPUT
#ifdef Py_CELLOBJECT_H
  LOGP("Py_CELLOBJECT_H inialized");
#endif

#ifdef Py_LIMITED_API
  LOGP("Py_LIMITED_API");
#endif

#ifdef PyCell_Get
  LOGP("PyCell_Get not defined");
#endif
LOGP("PyCell_Get defined");

#if PY_MAJOR_VERSION < 3
  initandroidembed();
#endif

  PyRun_SimpleString("import androidembed\nandroidembed.log('testing python "
                     "print redirection')");

  /* inject our bootstrap code to redirect python stdin/stdout
   * replace sys.path with our path
   */
  PyRun_SimpleString("import io, sys, posix\n");

  char add_site_packages_dir[256];

  if (dir_exists(python_bundle_dir)) {
    snprintf(add_site_packages_dir, 256,
             "sys.path.append('%s/site-packages')",
             python_bundle_dir);

    PyRun_SimpleString("import sys\n"
                       "sys.argv = ['notaninterpreterreally']\n"
                       "from os.path import realpath, join, dirname");
    PyRun_SimpleString(add_site_packages_dir);
    /* "sys.path.append(join(dirname(realpath(__file__)), 'site-packages'))") */
    PyRun_SimpleString("sys.path = ['.'] + sys.path");
  }

  PyRun_SimpleString(
      "class LogFile(io.IOBase):\n"
      "    def __init__(self):\n"
      "        self.__buffer = ''\n"
      "    def readable(self):\n"
      "        return False\n"
      "    def writable(self):\n"
      "        return True\n"
      "    def write(self, s):\n"
      "        s = self.__buffer + s\n"
      "        lines = s.split('\\n')\n"
      "        for l in lines[:-1]:\n"
      "            androidembed.log(l.replace('\\x00', ''))\n"
      "        self.__buffer = lines[-1]\n"
      "sys.stdout = sys.stderr = LogFile()\n"
      "print('Android path', sys.path)\n"
      "import os\n"
      "print('os.environ is', os.environ)\n"
      "print('Android kivy bootstrap done. __name__ is', __name__)");

#if PY_MAJOR_VERSION < 3
  PyRun_SimpleString("import site; print site.getsitepackages()\n");
#endif

  LOGP("AND: Ran string");

  /* run it !
   */
  LOGP("Run user program, change dir and execute entrypoint");

  /* Get the entrypoint, search the .pyc then .py
   */
  char *dot = strrchr(env_entrypoint, '.');
  char *ext = ".pyc";
  if (dot <= 0) {
    LOGP("Invalid entrypoint, abort.");
    return -1;
  }
  if (strlen(env_entrypoint) > ENTRYPOINT_MAXLEN - 2) {
      LOGP("Entrypoint path is too long, try increasing ENTRYPOINT_MAXLEN.");
      return -1;
  }
  if (!strcmp(dot, ext)) {
    if (!file_exists(env_entrypoint)) {
      /* fallback on .py */
      strcpy(entrypoint, env_entrypoint);
      entrypoint[strlen(env_entrypoint) - 1] = '\0';
      LOGP(entrypoint);
      if (!file_exists(entrypoint)) {
        LOGP("Entrypoint not found (.pyc, fallback on .py), abort");
        return -1;
      }
    } else {
      strcpy(entrypoint, env_entrypoint);
    }
  } else if (!strcmp(dot, ".py")) {
    /* if .py is passed, check the pyc version first */
    strcpy(entrypoint, env_entrypoint);
    entrypoint[strlen(env_entrypoint) + 1] = '\0';
    entrypoint[strlen(env_entrypoint)] = 'c';
    if (!file_exists(entrypoint)) {
      /* fallback on pure python version */
      if (!file_exists(env_entrypoint)) {
        LOGP("Entrypoint not found (.py), abort.");
        return -1;
      }
      strcpy(entrypoint, env_entrypoint);
    }
  } else {
    LOGP("Entrypoint have an invalid extension (must be .py or .pyc), abort.");
    return -1;
  }
  // LOGP("Entrypoint is:");
  // LOGP(entrypoint);
  fd = fopen(entrypoint, "r");
  if (fd == NULL) {
    LOGP("Open the entrypoint failed");
    LOGP(entrypoint);
    return -1;
  }

  /* run python !
   */
  ret = PyRun_SimpleFile(fd, entrypoint);
  fclose(fd);

  if (PyErr_Occurred() != NULL) {
    ret = 1;
    PyErr_Print(); /* This exits with the right code if SystemExit. */
    PyObject *f = PySys_GetObject("stdout");
    if (PyFile_WriteString("\n", f))
      PyErr_Clear();
  }

  LOGP("Python for android ended.");

  /* Shut down: since regular shutdown causes issues sometimes
     (seems to be an incomplete shutdown breaking next launch)
     we'll use sys.exit(ret) to shutdown, since that one works.

     Reference discussion:

     https://github.com/kivy/kivy/pull/6107#issue-246120816
   */
  char terminatecmd[256];
  snprintf(
    terminatecmd, sizeof(terminatecmd),
    "import sys; sys.exit(%d)\n", ret
  );
  PyRun_SimpleString(terminatecmd);

  /* This should never actually be reached, but we'll leave the clean-up
   * here just to be safe.
   */
#if PY_MAJOR_VERSION < 3
  Py_Finalize();
  LOGP("Unexpectedly reached Py_FinalizeEx(), but was successful.");
#else
  if (Py_FinalizeEx() != 0)  // properly check success on Python 3
    LOGP("Unexpectedly reached Py_FinalizeEx(), and got error!");
  else
    LOGP("Unexpectedly reached Py_FinalizeEx(), but was successful.");
#endif

  return ret;
}

JNIEXPORT void JNICALL Java_org_kivy_android_PythonService_nativeStart(
    JNIEnv *env,
    jobject thiz,
    jstring j_android_private,
    jstring j_android_argument,
    jstring j_service_entrypoint,
    jstring j_python_name,
    jstring j_python_home,
    jstring j_python_path,
    jstring j_arg) {
  jboolean iscopy;
  const char *android_private =
      (*env)->GetStringUTFChars(env, j_android_private, &iscopy);
  const char *android_argument =
      (*env)->GetStringUTFChars(env, j_android_argument, &iscopy);
  const char *service_entrypoint =
      (*env)->GetStringUTFChars(env, j_service_entrypoint, &iscopy);
  const char *python_name =
      (*env)->GetStringUTFChars(env, j_python_name, &iscopy);
  const char *python_home =
      (*env)->GetStringUTFChars(env, j_python_home, &iscopy);
  const char *python_path =
      (*env)->GetStringUTFChars(env, j_python_path, &iscopy);
  const char *arg = (*env)->GetStringUTFChars(env, j_arg, &iscopy);

  setenv("ANDROID_PRIVATE", android_private, 1);
  setenv("ANDROID_ARGUMENT", android_argument, 1);
  setenv("ANDROID_APP_PATH", android_argument, 1);
  setenv("ANDROID_ENTRYPOINT", service_entrypoint, 1);
  setenv("PYTHONOPTIMIZE", "2", 1);
  setenv("PYTHON_NAME", python_name, 1);
  setenv("PYTHONHOME", python_home, 1);
  setenv("PYTHONPATH", python_path, 1);
  setenv("PYTHON_SERVICE_ARGUMENT", arg, 1);
  setenv("P4A_BOOTSTRAP", bootstrap_name, 1);

  char *argv[] = {"."};
  /* ANDROID_ARGUMENT points to service subdir,
   * so main() will run main.py from this dir
   */
  main(1, argv);
}

#if defined(BOOTSTRAP_NAME_WEBVIEW) || defined(BOOTSTRAP_NAME_SERVICEONLY)
// Webview and service_only uses some more functions:

void Java_org_kivy_android_PythonActivity_nativeSetenv(
                                    JNIEnv* env, jclass cls,
                                    jstring name, jstring value)
//JNIEXPORT void JNICALL SDL_JAVA_INTERFACE(nativeSetenv)(
//                                    JNIEnv* env, jclass cls,
//                                    jstring name, jstring value)
{
    const char *utfname = (*env)->GetStringUTFChars(env, name, NULL);
    const char *utfvalue = (*env)->GetStringUTFChars(env, value, NULL);

    setenv(utfname, utfvalue, 1);

    (*env)->ReleaseStringUTFChars(env, name, utfname);
    (*env)->ReleaseStringUTFChars(env, value, utfvalue);
}


void Java_org_kivy_android_PythonActivity_nativeInit(JNIEnv* env, jclass cls, jobject obj)
{
  /* This nativeInit follows SDL2 */

  /* This interface could expand with ABI negotiation, calbacks, etc. */
  /* SDL_Android_Init(env, cls); */

  /* SDL_SetMainReady(); */

  /* Run the application code! */
  int status;
  char *argv[2];
  argv[0] = "Python_app";
  argv[1] = NULL;
  /* status = SDL_main(1, argv); */

  main(1, argv);

  /* Do not issue an exit or the whole application will terminate instead of just the SDL thread */
  /* exit(status); */
}
#endif

#endif

```

LOGS

```
2024-08-25 15:06:11.222 10443-10475 python                  org.test.test                        I  Initializing Python for Android
2024-08-25 15:06:11.222 10443-10475 python                  org.test.test                        I  Setting additional env vars from p4a_env_vars.txt
2024-08-25 15:06:11.222 10443-10475 python                  org.test.test                        I  Changing directory to the one provided by ANDROID_ARGUMENT
2024-08-25 15:06:11.222 10443-10475 python                  org.test.test                        I  /data/user/0/org.test.test/files/app
2024-08-25 15:06:11.224 10443-10475 python                  org.test.test                        I  Preparing to initialize python
2024-08-25 15:06:11.224 10443-10475 python                  org.test.test                        I  _python_bundle dir exists
2024-08-25 15:06:11.224 10443-10475 python                  org.test.test                        I  calculated paths to be...
2024-08-25 15:06:11.224 10443-10475 python                  org.test.test                        I  /data/user/0/org.test.test/files/app/_python_bundle/stdlib.zip:/data/user/0/org.test.test/files/app/_python_bundle/modules
2024-08-25 15:06:11.225 10443-10475 python                  org.test.test                        I  set wchar paths...
2024-08-25 15:06:11.237  1514-1514  GoogleInpu...hodService com...gle.android.inputmethod.latin  I  GoogleInputMethodService.onStartInput():1877 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=org.test.test fieldId=0 fieldName=null extras=null}, false)
2024-08-25 15:06:11.242 10443-10443 SDLThread               org.test.test                        W  type=1400 audit(0.0:119302): avc:  granted  { execute } for  path="/data/data/org.test.test/files/app/_python_bundle/modules/zlib.cpython-311.so" dev="dm-38" ino=377013 scontext=u:r:untrusted_app_30:s0:c39,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c39,c257,c512,c768 tclass=file app=org.test.test
2024-08-25 15:06:11.252 10443-10475 python                  org.test.test                        I  Initialized python
2024-08-25 15:06:11.252 10443-10475 python                  org.test.test                        I  AND: Init threads
2024-08-25 15:06:11.252 10443-10475 python                  org.test.test                        I  Py_CELLOBJECT_H inialized
2024-08-25 15:06:11.252 10443-10475 python                  org.test.test                        I  PyCell_Get defined
2024-08-25 15:06:11.252 10443-10475 python                  org.test.test                        I  testing python print redirection
2024-08-25 15:06:11.253 10443-10475 python                  org.test.test                        I  Android path ['.', '/data/user/0/org.test.test/files/app/_python_bundle/stdlib.zip', '/data/user/0/org.test.test/files/app/_python_bundle/modules', '/data/user/0/org.test.test/files/app/_python_bundle/site-packages']
2024-08-25 15:06:11.253 10443-10475 python                  org.test.test                        I  os.environ is environ({'PATH': '/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin', 'ANDROID_BOOTLOGO': '1', 'ANDROID_ROOT': '/system', 'ANDROID_ASSETS': '/system/app', 'ANDROID_DATA': '/data', 'ANDROID_STORAGE': '/storage', 'ANDROID_ART_ROOT': '/apex/com.android.art', 'ANDROID_I18N_ROOT': '/apex/com.android.i18n', 'ANDROID_TZDATA_ROOT': '/apex/com.android.tzdata', 'EXTERNAL_STORAGE': '/sdcard', 'ASEC_MOUNTPOINT': '/mnt/asec', 'DOWNLOAD_CACHE': '/data/cache', 'BOOTCLASSPATH': '/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/framework-graphics.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/apex/com.android.i18n/javalib/core-icu4j.jar:/apex/com.android.adservices/javalib/framework-adservices.jar:/apex/com.android.adservices/javalib/framework-sdksandbox.jar:/apex/com.android.appsearch/javalib/framework-appsearch.jar:/apex/com.android.btservices/javalib/framework-bluetooth.jar:/apex/com.android.configinfrastructure/javalib/framework-configinfrastructure.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.devicelock/javalib/framework-devicelock.jar:/apex/com.android.healthfitness/javalib/framework-healthfitness.jar:/apex/com.android.ipsec/javalib/android.net.ipsec.ike.jar:/apex/com.android.media/javalib/updatable-media.jar:/apex/com.android.mediaprovider/javalib/framework-mediaprovider.jar:/apex/com.android.ondevicepersonalization/javalib/framework-ondevicepersonalization.jar:/apex/com.android.os.statsd/javalib/framework-statsd.jar:/apex/com.android.permission/javalib/framework-permission.jar:/apex/com.android.permission/javalib/framework-permission-s.jar:/apex/com.android.scheduling/javalib/framework-scheduling.jar:/apex/com.android.sdkext/javalib/framework-sdkextensions.jar:/apex/com.android.tethering/javalib/framework-connectivity.jar:/apex/com.android.tethering/javalib/framework-connectivity-t.jar:/apex/com.android.tethering/javalib/framework-tethering.jar:/apex/com.android.uwb/javalib/framework-uwb.jar:/apex/com.android.virt/javalib/framework-virtualization.jar:/apex/com.android.wifi/javalib/framework-wifi.jar', 'DEX2OATBOOTCLASSPATH': '/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/framework-graphics.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/apex/com.android.i18n/javalib/core-icu4j.jar', 'SYSTEMSERVERCLASSPATH': '/system/framework/com.android.location.provider.jar:/system/framework/services.jar:/apex/com.android.adservices/javalib/service-adservices.jar:/apex/com.android.adservices/javalib/service-sdksandbox.jar:/apex/com.android.appsearch/javalib/service-appsearch.jar:/apex/com.android.art/javalib/service-art.jar:/apex/com.android.configinfrastructure/javalib/service-configinfrastructure.jar:/apex/com.android.healthfitness/javalib/service-healthfitness.jar:/apex/com.android.media/javalib/service-media-s.jar:/apex/com.android.ondevicepersonalization/javalib/service-ondevicepersonalization.jar:/apex/com.android.permission/javalib/service-permission.jar:/apex/com.android.rkpd/javalib/service-rkp.jar', 'STANDALONE_SYSTEMSERVER_JARS': '/apex/com.android.btservices/javalib/service-bluetooth.jar:/apex/com.android.devicelock/javalib/service-devicelock.jar:/apex/com.android.os.statsd/javalib/service-statsd.jar:/apex/com.android.scheduling/javalib/service-scheduling.jar:/apex/com.android.tethering/javalib/service-connectivity.jar:/apex/com.android.uwb/javalib/s
2024-08-25 15:06:11.253 10443-10475 python                  org.test.test                        I  Android kivy bootstrap done. __name__ is __main__
2024-08-25 15:06:11.253 10443-10475 python                  org.test.test                        I  AND: Ran string
2024-08-25 15:06:11.253 10443-10475 python                  org.test.test                        I  Run user program, change dir and execute entrypoint
2024-08-25 15:06:11.262 10443-10443 SDLThread               org.test.test                        W  type=1400 audit(0.0:119303): avc:  granted  { execute } for  path="/data/data/org.test.test/files/app/_python_bundle/modules/_lzma.cpython-311.so" dev="dm-38" ino=376968 scontext=u:r:untrusted_app_30:s0:c39,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c39,c257,c512,c768 tclass=file app=org.test.test
2024-08-25 15:06:11.270 10443-10443 SDLThread               org.test.test                        W  type=1400 audit(0.0:119304): avc:  granted  { execute } for  path="/data/data/org.test.test/files/app/_python_bundle/modules/_typing.cpython-311.so" dev="dm-38" ino=376993 scontext=u:r:untrusted_app_30:s0:c39,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c39,c257,c512,c768 tclass=file app=org.test.test
2024-08-25 15:06:11.282 10443-10443 SDLThread               org.test.test                        W  type=1400 audit(0.0:119305): avc:  granted  { execute } for  path="/data/data/org.test.test/files/app/_python_bundle/modules/math.cpython-311.so" dev="dm-38" ino=377002 scontext=u:r:untrusted_app_30:s0:c39,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c39,c257,c512,c768 tclass=file app=org.test.test
2024-08-25 15:06:11.282 10443-10443 SDLThread               org.test.test                        W  type=1400 audit(0.0:119306): avc:  granted  { execute } for  path="/data/data/org.test.test/files/app/_python_bundle/modules/_heapq.cpython-311.so" dev="dm-38" ino=376965 scontext=u:r:untrusted_app_30:s0:c39,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c39,c257,c512,c768 tclass=file app=org.test.test
2024-08-25 15:06:11.298 10443-10475 python                  org.test.test                        I  [ERROR  ] Error when copying logo directory
2024-08-25 15:06:11.298 10443-10475 python                  org.test.test                        I  Traceback (most recent call last):
2024-08-25 15:06:11.298 10443-10475 python                  org.test.test                        I    File "/Users/leonidgvozdev/Work/example/.buildozer/android/platform/build-armeabi-v7a_arm64-v8a/build/python-installs/Test/arm64-v8a/kivy/__init__.py", line 372, in <module>
2024-08-25 15:06:11.298 10443-10475 python                  org.test.test                        I    File "/Users/leonidgvozdev/Work/example/.buildozer/android/platform/build-armeabi-v7a_arm64-v8a/build/other_builds/python3/arm64-v8a__ndk_target_21/python3/Lib/shutil.py", line 561, in copytree
2024-08-25 15:06:11.298 10443-10475 python                  org.test.test                        I    File "/Users/leonidgvozdev/Work/example/.buildozer/android/platform/build-armeabi-v7a_arm64-v8a/build/other_builds/python3/arm64-v8a__ndk_target_21/python3/Lib/shutil.py", line 515, in _copytree
2024-08-25 15:06:11.298 10443-10475 python                  org.test.test                        I  shutil.Error: [('/data/user/0/org.test.test/files/app/_python_bundle/site-packages/kivy/data/logo/kivy-icon-128.png', '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-128.png', "[Errno 13] Permission denied: '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-128.png'"), ('/data/user/0/org.test.test/files/app/_python_bundle/site-packages/kivy/data/logo/kivy-icon-16.png', '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-16.png', "[Errno 13] Permission denied: '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-16.png'"), ('/data/user/0/org.test.test/files/app/_python_bundle/site-packages/kivy/data/logo/kivy-icon-24.png', '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-24.png', "[Errno 13] Permission denied: '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-24.png'"), ('/data/user/0/org.test.test/files/app/_python_bundle/site-packages/kivy/data/logo/kivy-icon-256.png', '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-256.png', "[Errno 13] Permission denied: '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-256.png'"), ('/data/user/0/org.test.test/files/app/_python_bundle/site-packages/kivy/data/logo/kivy-icon-32.png', '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-32.png', "[Errno 13] Permission denied: '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-32.png'"), ('/data/user/0/org.test.test/files/app/_python_bundle/site-packages/kivy/data/logo/kivy-icon-48.png', '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-48.png', "[Errno 13] Permission denied: '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-48.png'"), ('/data/user/0/org.test.test/files/app/_python_bundle/site-packages/kivy/data/logo/kivy-icon-512.png', '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-512.png', "[Errno 13] Permission denied: '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-512.png'"), ('/data/user/0/org.test.test/files/app/_python_bundle/site-packages/kivy/data/logo/kivy-icon-64.ico', '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-64.ico', "[Errno 13] Permission denied: '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-64.ico'"), ('/data/user/0/org.test.test/files/app/_python_bundle/site-packages/kivy/data/logo/kivy-icon-64.png', '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-64.png', "[Errno 13] Permission denied: '/data/user/0/org.test.test/files/app/.kivy/icon/kivy-icon-64.png'"), ('/data/user/0/org.test.test/files/app/_python_bundle/site-packages/kivy/data/logo', '/data/user/0/org.test.test/files/app/.kivy/icon', "[Errno 13] Permission denied: '/data/user/0/org.test.test/files/app/.kivy/icon'")]
2024-08-25 15:06:11.301 10443-10475 python                  org.test.test                        I  [WARNING] [Config      ] Older configuration version detected (0 instead of 27)
2024-08-25 15:06:11.302 10443-10475 python                  org.test.test                        I  [WARNING] [Config      ] Upgrading configuration in progress.
2024-08-25 15:06:11.302 10443-10475 python                  org.test.test                        I  [DEBUG  ] [Config      ] Upgrading from 0 to 1
2024-08-25 15:06:11.303 10443-10475 python                  org.test.test                        I  [INFO   ] [Logger      ] Record log in /data/user/0/org.test.test/files/app/.kivy/logs/kivy_24-08-25_0.txt
2024-08-25 15:06:11.304 10443-10475 python                  org.test.test                        I  [INFO   ] [Kivy        ] v2.3.0
2024-08-25 15:06:11.304 10443-10475 python                  org.test.test                        I  [INFO   ] [Kivy        ] Installed at "/data/user/0/org.test.test/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
2024-08-25 15:06:11.304 10443-10475 python                  org.test.test                        I  [INFO   ] [Python      ] v3.11.5 (main, Aug 25 2024, 14:57:03) [Clang 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0
2024-08-25 15:06:11.304 10443-10475 python                  org.test.test                        I  [INFO   ] [Python      ] Interpreter at ""
2024-08-25 15:06:11.305 10443-10475 python                  org.test.test                        I  [INFO   ] [Logger      ] Purge log fired. Processing...
2024-08-25 15:06:11.305 10443-10475 python                  org.test.test                        I  [INFO   ] [Logger      ] Purge finished!
2024-08-25 15:06:11.517 10443-10475 python                  org.test.test                        I  [INFO   ] [Factory     ] 195 symbols loaded
2024-08-25 15:06:11.530 10443-10475 python                  org.test.test                        I  [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
2024-08-25 15:06:11.598 10443-10475 python                  org.test.test                        I  [INFO   ] [Text        ] Provider: sdl2
2024-08-25 15:06:11.637 10443-10475 python                  org.test.test                        I   Traceback (most recent call last):
2024-08-25 15:06:11.637 10443-10475 python                  org.test.test                        I     File "/Users/leonidgvozdev/Work/example/.buildozer/android/app/main.py", line 40, in <module>
2024-08-25 15:06:11.637 10443-10475 python                  org.test.test                        I     File "/Users/leonidgvozdev/Work/example/.buildozer/android/app/test.py", line 2, in <module>
2024-08-25 15:06:11.637 10443-10475 python                  org.test.test                        I     File "/Users/leonidgvozdev/Work/example/.buildozer/android/app/pyarmor_runtime_005896/__init__.py", line 53, in <module>
2024-08-25 15:06:11.637 10443-10475 python                  org.test.test                        I     File "/Users/leonidgvozdev/Work/example/.buildozer/android/app/pyarmor_runtime_005896/__init__.py", line 52, in __pyarmor__
2024-08-25 15:06:11.637 10443-10475 python                  org.test.test                        I   RuntimeError: failed to get api PyCell_Get
```

As you can see `PyCell_Get` found and available

**Comment by GvozdevLeonid** [comment]
@jondy I changed patchelf from `libpython3.11.so` to `libmain.so` -> error with `PyBytes_AsStringAndSize` is missing, but error with `PyCell_Get` still occured

**Comment by jondy** [comment]
Well, I upload pre-release package
https://pyarmor.dashingsoft.com/downloads/temp/pyarmor.cli.core.android-6.5.3.post1-cp311-none-any.whl

Try to download it, and install it.

It should fix this issue if bcc mode is not enabled

**Comment by GvozdevLeonid** [comment]
Yes, it works! Thank you very much!

Will these android builds be available on pypi later?

**Comment by GvozdevLeonid** [comment]
I have one question left, which is poorly covered in the documentation. If I understand correctly, the pyarmor_runtime.so file is immutable and all flags like --period --outer and others do not affect it, so I can confuse the code by referring to the same pyarmor_runtime.so every time?

Also, as I understood, when specifying the --outer flag, I can later replace the key file with a new one without harm.

**Comment by jondy** [comment]
I have uploaded them to pypi, now it's available by `pip install pyarmor.cli.android>=6.5.3.post1`

> so I can confuse the code by referring to the same pyarmor_runtime.so every time

Are you sure `pyarmor_time.so` is same when different options like `--period` are used? Try to compare them.

**Comment by irhamdz** [comment]
hi i also got the same error, are the fix is same?
ImportError: dlopen failed: cannot locate symbol "PyBytes_AsStringAndSize" referenced by "/data/data/com.termux/files/home/blum-query-id/pyarmor_runtime_004817/android_aarch64/pyarmor_runtime.so"
